### ISSUE TITLE
Python 2.7 Support Issue

### ISSUE THREAD

**Issue by AhnSeongHyun** [pyexcel/pyexcel-xlsx#10]
#$ pip install pyexcel-xlsx
Downloading/unpacking pyexcel-xlsx
  Downloading pyexcel-xlsx-0.2.1.zip
  Running setup.py (path:/tmp/pip_build_root/pyexcel-xlsx/setup.py) egg_info for package pyexcel-xlsx

Downloading/unpacking openpyxl>=2.2.2 (from pyexcel-xlsx)
  Downloading openpyxl-2.3.5.tar.gz (141kB): 141kB downloaded
  Running setup.py (path:/tmp/pip_build_root/openpyxl/setup.py) egg_info for package openpyxl

    no previously-included directories found matching 'openpyxl/tests'
    no previously-included directories found matching 'openpyxl/sample'
    no previously-included directories found matching 'openpyxl/benchmarks'
    no previously-included directories found matching 'openpyxl/develop'
    warning: no previously-included files matching 'test_*.py' found under directory 'openpyxl'
    warning: no previously-included files matching 'tests/*.py' found under directory 'openpyxl'
Downloading/unpacking pyexcel-io>=0.1.0 (from pyexcel-xlsx)
  Downloading pyexcel-io-0.2.1.zip
  Running setup.py (path:/tmp/pip_build_root/pyexcel-io/setup.py) egg_info for package pyexcel-io
    error in pyexcel-io setup command: Invalid environment marker: python_version<"2.7"
    Complete output from command python setup.py egg_info:
    error in pyexcel-io setup command: Invalid environment marker: python_version<"2.7"

----------------------------------------

**Comment by chfw** [comment]
Sorry about the problem. There was special note in [the installation](https://github.com/pyexcel/pyexcel-xlsx#installation). Please upgrade your setuptools.
