### ISSUE TITLE
use optimized writer for writing out xlsx so as to support large files

### ISSUE THREAD

**Issue by chfw** [pyexcel/pyexcel-xlsx#11]
optimized writer is a better fit for pyexcel-xlsx.

trigger: https://github.com/pyexcel/Flask-Excel/issues/16
hint: http://stackoverflow.com/questions/21328884/openpyxl-writing-large-excel-files-with-python
doc: http://openpyxl.readthedocs.io/en/2.3.3/optimized.html

**Comment by chfw** [comment]
to evaluate before its release:

    pip install https://github.com/pyexcel/pyexcel-io/archive/master.zip
    pip install https://github.com/pyexcel/pyexcel-xlsx/archive/master.zip

**Comment by rotten** [comment]
Thanks, I'll give it a try tomorrow.

**Comment by rotten** [comment]
It seems to work.  I'm not sure it is faster than the xlsxw solution, but it seems to be fairly stable and so far I haven't been able to crash it with large data sets.  :-)  Thanks.

**Comment by chfw** [comment]
So it seems the following promise of "write-only" from openpyxl is valid.

> It is able to export unlimited amount of data (even more than Excel can handle actually), while keeping memory usage under 10Mb.
