### ISSUE TITLE
Packaging with PyInstaller not work even following the doc

### ISSUE THREAD

**Issue by xiazhibin** [pyexcel/pyexcel-xlsx#32]
I add below command in PyInstaller:
```
--hidden-import pyexcel_xlsx
--hidden-import pyexcel_xlsx.xlsxr
--hidden-import pyexcel_xlsx.xlsxw
``` 

Here is the PyInstaller output:
```
3446 INFO: Analyzing hidden import 'pyexcel_xlsx'
3599 INFO: Analyzing hidden import 'pyexcel_xlsx.xlsxr'
5194 INFO: Analyzing hidden import 'pyexcel_xlsx.xlsxw'
```

But when I run, I still get
`Please install one of these plugins for read data in 'xlsx': pyexcel-xls,pyexcel-xlsx`

Mac OS
Python3.6.4
pyexcel (0.5.13)
pyexcel-io (0.5.16)
pyexcel-webio (0.1.4)
pyexcel-xlsx (0.5.7)
PyInstaller (3.4)

**Comment by chfw** [comment]
I supposed you succeeded in it.
