### ISSUE TITLE
openpyxl newer versions

### ISSUE THREAD

**Issue by Thimxx** [pyexcel/pyexcel-xlsx#34]
Openpyxl (https://pypi.org/project/openpyxl/) has created new versions. In the dependencies of the code it appears 2.6.0 as the most recent one which is 1 year old.

Is it possible to update the dependency to the latest version (3.0.2)?

**Comment by chfw** [comment]
I will look at it after my holidays. It was introduced because of https://github.com/pyexcel/pyexcel-io/issues/66

**Comment by Thimxx** [comment]
The reported error you refer happened on 14th Feb, with version 2.6.0, there was a release in March, the 2.6.1. It might be only the version 2.6.0.

Here is the list of versions

https://openpyxl.readthedocs.io/en/stable/changes.html#id31

Thanks!

**Comment by wind39** [comment]
Hi,

The issue https://github.com/pyexcel/pyexcel-io/issues/66 was fixed here: https://bitbucket.org/openpyxl/openpyxl/issues/1191

Best regards,

William

**Comment by Thimxx** [comment]
Thanks @wind39 , actually the issue you refer points to an error in v2.6, so the actual incompatibiliy should be limited to 2.6(plus any new development during this year)

**Comment by chfw** [comment]
released!

**Comment by chfw** [comment]
just to confirm, the issue was with 2.6.0 only.

**Comment by wind39** [comment]
Hi @chfw ,

Thank you very much! :)

Regards,

William
