### ISSUE TITLE
Python 2.7.18：No handlers could be found for logger "lml.utils"

### ISSUE THREAD

**Issue by worldg** [pyexcel/pyexcel-xlsx#46]
C:\Python27\Scripts>pip2 install pyexcel pyexcel-xls pyexcel-xlsx xlrd xlwt openpyxl
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: pyexcel in c:\python27\lib\site-packages (0.5.15)
Requirement already satisfied: pyexcel-xls in c:\python27\lib\site-packages (0.6.0)
Requirement already satisfied: pyexcel-xlsx in c:\python27\lib\site-packages (0.5.8)
Requirement already satisfied: xlrd in c:\python27\lib\site-packages (1.2.0)
Requirement already satisfied: xlwt in c:\python27\lib\site-packages (1.3.0)
Requirement already satisfied: openpyxl in c:\python27\lib\site-packages (2.6.4)
Requirement already satisfied: texttable>=0.8.2 in c:\python27\lib\site-packages (from pyexcel) (1.6.3)
Requirement already satisfied: pyexcel-io>=0.5.19 in c:\python27\lib\site-packages (from pyexcel) (0.5.20)
Requirement already satisfied: lml>=0.0.4 in c:\python27\lib\site-packages (from pyexcel) (0.0.9)
Requirement already satisfied: jdcal in c:\python27\lib\site-packages (from openpyxl) (1.4.1)
Requirement already satisfied: et_xmlfile in c:\python27\lib\site-packages (from openpyxl) (1.0.1)

import pyexcel
No handlers could be found for logger "lml.utils"

**Comment by chfw** [comment]
Which package complains about it? More trace?

Ps，Did you read the end of life notice for python 2.7?
